on: [push, pull_request]

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: cicd
      run: |
        pwd && ls -lash
        ./.cicd/build-push.sh