on: [push, pull_request]

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: cicd
      run: |
        docker build -f ./docker/paper.Dockerfile -t server .